-- MySQL Script generated by MySQL Workbench
-- Sat May  2 15:52:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vncubing
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vncubing` ;

-- -----------------------------------------------------
-- Schema vncubing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vncubing` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vncubing` ;

-- -----------------------------------------------------
-- Table `vncubing`.`competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competitions` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competitions` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`competitions` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_info_tabs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_info_tabs` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_info_tabs` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `data` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `comp_info_tab_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`competition_info_tabs` (`id` ASC) VISIBLE;

CREATE INDEX `comp_info_tab_comp_idx` ON `vncubing`.`competition_info_tabs` (`competition_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`users` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `wca_id` VARCHAR(10) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `refresh_token` VARCHAR(36) NULL DEFAULT NULL,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`users` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `wca_id_UNIQUE` ON `vncubing`.`users` (`wca_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_organizers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_organizers` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_organizers` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `competition`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`),
  CONSTRAINT `organizer`
    FOREIGN KEY (`user_id`)
    REFERENCES `vncubing`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`competition_organizers` (`id` ASC) VISIBLE;

CREATE INDEX `competition_idx` ON `vncubing`.`competition_organizers` (`competition_id` ASC) VISIBLE;

CREATE INDEX `organizer_idx` ON `vncubing`.`competition_organizers` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_registrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_registrations` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_registrations` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `registration_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`),
  CONSTRAINT `registration_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vncubing`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`competition_registrations` (`id` ASC) VISIBLE;

CREATE INDEX `competition_idx` ON `vncubing`.`competition_registrations` (`competition_id` ASC) VISIBLE;

CREATE INDEX `user_idx` ON `vncubing`.`competition_registrations` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_rounds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_rounds` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_rounds` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `event_id` VARCHAR(20) NOT NULL,
  `round_type` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `comp_round_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`competition_rounds` (`id` ASC) VISIBLE;

CREATE INDEX `comp_round_comp_idx` ON `vncubing`.`competition_rounds` (`competition_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_time_segments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_time_segments` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_time_segments` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `round_id` VARCHAR(36) NULL DEFAULT NULL,
  `start_at` TIMESTAMP(1) NOT NULL,
  `end_at` TIMESTAMP(1) NOT NULL,
  `display_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `comp_time_segment_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`),
  CONSTRAINT `comp_time_segment_round`
    FOREIGN KEY (`round_id`)
    REFERENCES `vncubing`.`competition_rounds` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`competition_time_segments` (`id` ASC) VISIBLE;

CREATE INDEX `comp_time_segment_comp_idx` ON `vncubing`.`competition_time_segments` (`competition_id` ASC) VISIBLE;

CREATE INDEX `comp_time_segment_round_idx` ON `vncubing`.`competition_time_segments` (`round_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`results` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`results` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `round_id` VARCHAR(36) NOT NULL,
  `best` INT NOT NULL,
  `average` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `result_round`
    FOREIGN KEY (`round_id`)
    REFERENCES `vncubing`.`competition_rounds` (`id`),
  CONSTRAINT `result_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vncubing`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vncubing`.`results` (`id` ASC) VISIBLE;

CREATE INDEX `result_user_idx` ON `vncubing`.`results` (`user_id` ASC) VISIBLE;

CREATE INDEX `result_round_idx` ON `vncubing`.`results` (`round_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `vncubing`.`result_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`result_attempts` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`result_attempts` (
  `result_id` VARCHAR(36) NOT NULL,
  `attempt_number` TINYINT UNSIGNED NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`result_id`, `attempt_number`),
  CONSTRAINT `attempt_result`
    FOREIGN KEY (`result_id`)
    REFERENCES `vncubing`.`results` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
