-- MySQL Script generated by MySQL Workbench
-- Sun May 10 10:43:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vncubing
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vncubing` ;

-- -----------------------------------------------------
-- Schema vncubing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vncubing` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vncubing` ;

-- -----------------------------------------------------
-- Table `vncubing`.`competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competitions` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competitions` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `competitor_limit` INT NULL DEFAULT NULL,
  `is_online` TINYINT NOT NULL DEFAULT '0',
  `registration_start_time` TIMESTAMP(1) NOT NULL,
  `registration_end_time` TIMESTAMP(1) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_rounds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_rounds` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_rounds` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `event_id` VARCHAR(25) NOT NULL,
  `round_type_id` VARCHAR(1) NOT NULL,
  `format_id` VARCHAR(1) NOT NULL,
  `time_limit` INT NULL DEFAULT NULL,
  `cutoff_attempts` TINYINT NULL DEFAULT NULL,
  `cutoff_result` INT NULL DEFAULT NULL,
  `advancement_condition_type` VARCHAR(15) NULL DEFAULT NULL,
  `advancement_condition_value` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `comp_round_comp_idx` (`competition_id` ASC) VISIBLE,
  CONSTRAINT `comp_round_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_activities` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_activities` (
  `id` VARCHAR(36) NOT NULL,
  `display_name` VARCHAR(45) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `round_id` VARCHAR(36) NULL DEFAULT NULL,
  `start_time` TIMESTAMP(1) NOT NULL,
  `end_time` TIMESTAMP(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `comp_activity_comp_idx` (`competition_id` ASC) VISIBLE,
  INDEX `comp_activity_round_idx` (`round_id` ASC) VISIBLE,
  CONSTRAINT `fk_comp_activity`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`),
  CONSTRAINT `fk_round_activity`
    FOREIGN KEY (`round_id`)
    REFERENCES `vncubing`.`competition_rounds` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_info_tabs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_info_tabs` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_info_tabs` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `data` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `comp_info_tab_comp_idx` (`competition_id` ASC) VISIBLE,
  CONSTRAINT `comp_info_tab_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`users` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `wca_id` VARCHAR(10) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `hashed_password` VARCHAR(100) NULL DEFAULT NULL,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `wca_id_UNIQUE` (`wca_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_organizers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_organizers` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_organizers` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `competition_idx` (`competition_id` ASC) VISIBLE,
  INDEX `organizer_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `competition`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`),
  CONSTRAINT `organizer`
    FOREIGN KEY (`user_id`)
    REFERENCES `vncubing`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_registrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_registrations` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_registrations` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `created_at` TIMESTAMP(1) NOT NULL,
  `updated_at` TIMESTAMP(1) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `competition_idx` (`competition_id` ASC) VISIBLE,
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `registration_comp`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`),
  CONSTRAINT `registration_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vncubing`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`competition_venues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`competition_venues` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`competition_venues` (
  `id` VARCHAR(36) NOT NULL,
  `competition_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `province` VARCHAR(20) NOT NULL,
  `latitude_microdegrees` INT NOT NULL,
  `longitude_microdegrees` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `competition_idx` (`competition_id` ASC) VISIBLE,
  CONSTRAINT `competition_venue`
    FOREIGN KEY (`competition_id`)
    REFERENCES `vncubing`.`competitions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`results` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`results` (
  `id` VARCHAR(36) NOT NULL,
  `round_id` VARCHAR(36) NOT NULL,
  `best` INT NOT NULL,
  `average` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `result_round_idx` (`round_id` ASC) VISIBLE,
  CONSTRAINT `result_round`
    FOREIGN KEY (`round_id`)
    REFERENCES `vncubing`.`competition_rounds` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`result_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`result_attempts` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`result_attempts` (
  `result_id` VARCHAR(36) NOT NULL,
  `attempt_number` TINYINT UNSIGNED NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`result_id`, `attempt_number`),
  CONSTRAINT `attempt_result`
    FOREIGN KEY (`result_id`)
    REFERENCES `vncubing`.`results` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`result_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`result_users` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`result_users` (
  `result_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`result_id`, `user_id`),
  INDEX `result_user_result_idx` (`result_id` ASC) VISIBLE,
  INDEX `result_user_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `result_user_result`
    FOREIGN KEY (`result_id`)
    REFERENCES `vncubing`.`results` (`id`),
  CONSTRAINT `result_user_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vncubing`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vncubing`.`time_limit_cumulative_rounds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vncubing`.`time_limit_cumulative_rounds` ;

CREATE TABLE IF NOT EXISTS `vncubing`.`time_limit_cumulative_rounds` (
  `id` VARCHAR(36) NOT NULL,
  `round_id` VARCHAR(36) NOT NULL,
  `cumulative_round_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `round_id` (`round_id` ASC) VISIBLE,
  INDEX `cumulative_round_idx` (`cumulative_round_id` ASC) VISIBLE,
  CONSTRAINT `cumulative_round`
    FOREIGN KEY (`cumulative_round_id`)
    REFERENCES `vncubing`.`competition_rounds` (`id`),
  CONSTRAINT `round`
    FOREIGN KEY (`round_id`)
    REFERENCES `vncubing`.`competition_rounds` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
